# Generated by Django 3.2.9 on 2021-11-30 10:32

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mintonplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mintongym',
            name='running_time',
        ),
        migrations.AddField(
            model_name='mintongym',
            name='endtime',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='종료 시간'),
        ),
        migrations.AddField(
            model_name='mintongym',
            name='explain',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='설명'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mintongym',
            name='starttime',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='시작 시간'),
        ),
    ]
