# Generated by Django 3.2.9 on 2021-11-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mintonplace', '0002_auto_20211130_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mintongym',
            name='contact',
            field=models.CharField(max_length=11, verbose_name='연락처'),
        ),
    ]
