# Generated by Django 3.2.9 on 2021-11-30 11:46

import datetime
from django.db import migrations, models
import django.utils.timezone
import mintonplace.upload_to


class Migration(migrations.Migration):

    dependencies = [
        ('mintonplace', '0003_alter_mintongym_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='mintongym',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mintongym',
            name='photo',
            field=models.ImageField(blank=True, upload_to=mintonplace.upload_to.uuid_name_upload_to),
        ),
        migrations.AddField(
            model_name='mintongym',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mintongym',
            name='contact',
            field=models.CharField(blank=True, max_length=11, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='mintongym',
            name='endtime',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), verbose_name='종료 시간'),
        ),
        migrations.AlterField(
            model_name='mintongym',
            name='explain',
            field=models.TextField(blank=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='mintongym',
            name='starttime',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), verbose_name='시작 시간'),
        ),
    ]
