# Generated by Django 3.2.9 on 2021-12-08 06:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='태그')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='민턴장 이름')),
                ('address', models.CharField(max_length=100, verbose_name='주소')),
                ('telephone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{3,4}-?\\d{3,4}-?\\d{4}$', message='전화번호를 입력해주세요.')], verbose_name='전화번호')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='사진')),
                ('tag_set', models.ManyToManyField(to='mintonplace.Tag')),
            ],
            options={
                'verbose_name': '포스팅',
                'verbose_name_plural': '포스팅 목록',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=30, verbose_name='글쓴이')),
                ('message', models.TextField(verbose_name='댓글')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mintonplace.post')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글 목록',
            },
        ),
    ]
