# Generated by Django 3.2.9 on 2021-12-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badminton', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minton',
            name='open_at',
        ),
        migrations.AddField(
            model_name='minton',
            name='parking',
            field=models.BooleanField(blank=True, default=1, verbose_name='주차장 보유'),
            preserve_default=False,
        ),
    ]
