# Generated by Django 3.2.9 on 2021-12-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badminton', '0002_auto_20211204_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='minton',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='minton',
            name='telephone',
            field=models.CharField(blank=True, max_length=13, verbose_name='연락처'),
        ),
    ]
