# Generated by Django 3.2.9 on 2021-12-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badminton', '0002_minton_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minton',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='사진'),
        ),
    ]
