# Generated by Django 3.2.9 on 2021-12-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badminton', '0003_auto_20211204_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minton',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='체육관명'),
        ),
    ]
