# Generated by Django 3.2.9 on 2021-11-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badmintonplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='민턴장 이름')),
                ('address', models.CharField(max_length=100, verbose_name='주소')),
                ('phone_num', models.CharField(max_length=11, verbose_name='연락처')),
                ('homepage', models.CharField(blank=True, max_length=200, null=True, verbose_name='홈페이지')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='이메일')),
                ('parking', models.BooleanField(verbose_name='주차장 보유 여부')),
            ],
        ),
    ]
