# Generated by Django 3.2.9 on 2021-12-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catube', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail',
            new_name='thumbnail_file',
        ),
    ]
